# baseURL = "http://example.org/"
baseURL = "http://test.superpowergalaxy.com.s3-website-us-east-1.amazonaws.com/"
title = "Jingyu Su"
languageCode = "en-us"
theme = "ananke"


[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://test.superpowergalaxy.com/?region=us-east-1" #your bucket here


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-157146402-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.7
  filename = "sitemap.xml"

[params]
  favicon = ""
  new-window = ""
  description = "My persional website."
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/superpowergalaxy/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jingyusu/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cropped.jpg"
  recent_posts_number = 5
